### ISSUE TITLE
皇帝的新发布版。。。

### ISSUE THREAD

**Issue by deep-dark-forest** [allMagicNB/AM-ToolBox#1]

**Comment by allMagicNB** [comment]
你在做啥？？？

**Comment by deep-dark-forest** [comment]
今天随便翻到的，看了下readme，感觉不对劲，这好像release是空的啊……

**Comment by allMagicNB** [comment]
> 今天随便翻到的，看了下readme，感觉不对劲，这好像release是空的啊……

额，这个项目是真实存在的，但是太久没维护和上传代码……
最近要参加比赛，把这个玩意顺便拿来用了（
